# Generated by Django 6.0.1 on 2026-01-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=5000)),
                ("amazon_id", models.CharField(max_length=50)),
                ("current_price", models.CharField(max_length=20)),
                ("amazon_affiliate_link", models.CharField(max_length=200)),
                ("primary_photo_link", models.CharField(max_length=500)),
            ],
        ),
    ]
