# Generated by Django 6.0.1 on 2026-01-27 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "department_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=5000)),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="is_best_seller",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="is_hot_deal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="department",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.department",
            ),
        ),
    ]
