# Generated by Django 6.0.1 on 2026-01-27 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_department_product_is_best_seller_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="department",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.department",
            ),
        ),
    ]
