# Generated by Django 6.0.1 on 2026-01-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_name", models.CharField(max_length=1000)),
                ("tag_value", models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_best_seller",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_hot_deal",
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="products.tag"
            ),
        ),
    ]
