# Generated by Django 6.0.1 on 2026-01-29 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_tag_remove_product_is_best_seller_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="department_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
