# Generated by Django 6.0.1 on 2026-01-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_department_department_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_percentage",
            field=models.IntegerField(default=0),
        ),
    ]
